name: Code Quality

on:
  push:
    branches: [master]
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check branch_helper bin"
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check branch_helper bin"
